openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Success
  /users/{userId}/orders:
    get:
      summary: Get user orders
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
        '400':
          description: Bad Request
        '404':
          description: User not found
    post:
      summary: Create user order
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: string
      - name: order
        in: header
        description: Order details
        required: true
        schema:
          type: object
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
        '400':
          description: Bad Request
        '404':
          description: User not found
  /users/{userId}/orders/{orderId}:
    delete:
      summary: Delete order by ID
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: string
      - name: orderId
        in: path
        description: Order ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
        '400':
          description: Bad Request
        '404':
          description: Order not found
components:
  schemas: {}
